### ISSUE TITLE
Does not work with compact width, ie iPhone

### ISSUE THREAD

**Issue by newmanw** [dstarsboy/TMMultiDetailSplitView#2]
The great part about a split view controller is that its is context specific based on width (compact or regular).  This only works for regular width devices.

**Comment by trav-ma** [comment]
Good point. This demo was simply for showing how to segue and I had the app locked in to iPad device. I just updated it to be universal and work appropriately. Thanks

**Comment by giofid** [comment]
In my opinion, in the iPhone doesn't work appropriately. The detail view is modal showed when I tap in a master cell and it's not pushed in the master view navigation controller
